AWSTemplateFormatVersion: '2010-09-09'
Description: 'CloudWatch Alarms for Excel Template Mapper'

Parameters:
  Environment:
    Type: String
    Default: 'dev'
    Description: Environment name
  
  ProjectName:
    Type: String
    Default: 'excel-template-mapper'
    Description: Project name
    
  NotificationEmail:
    Type: String
    Description: Email address for alarm notifications
    Default: 'admin@example.com'

Resources:
  # SNS Topic for Notifications
  AlarmNotificationTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: !Sub '${ProjectName}-alarms-${Environment}'
      DisplayName: 'Excel Template Mapper Alarms'
      Subscription:
        - Protocol: email
          Endpoint: !Ref NotificationEmail

  # Lambda Function Alarms
  LambdaHighErrorRateAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub '${ProjectName}-lambda-high-error-rate-${Environment}'
      AlarmDescription: 'Lambda function error rate is above 5%'
      MetricName: ErrorRate
      Namespace: AWS/Lambda
      Statistic: Average
      Period: 300
      EvaluationPeriods: 2
      DatapointsToAlarm: 2
      Threshold: 5
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: FunctionName
          Value: !Sub '${ProjectName}-main-${Environment}'
      AlarmActions:
        - !Ref AlarmNotificationTopic
      OKActions:
        - !Ref AlarmNotificationTopic
      TreatMissingData: notBreaching

  LambdaHighDurationAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub '${ProjectName}-lambda-high-duration-${Environment}'
      AlarmDescription: 'Lambda function duration is consistently high'
      MetricName: Duration
      Namespace: AWS/Lambda
      Statistic: Average
      Period: 300
      EvaluationPeriods: 3
      DatapointsToAlarm: 3
      Threshold: 250000  # 250 seconds (close to 5min timeout)
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: FunctionName
          Value: !Sub '${ProjectName}-main-${Environment}'
      AlarmActions:
        - !Ref AlarmNotificationTopic
      TreatMissingData: notBreaching

  LambdaThrottleAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub '${ProjectName}-lambda-throttles-${Environment}'
      AlarmDescription: 'Lambda function is being throttled'
      MetricName: Throttles
      Namespace: AWS/Lambda
      Statistic: Sum
      Period: 300
      EvaluationPeriods: 1
      DatapointsToAlarm: 1
      Threshold: 1
      ComparisonOperator: GreaterThanOrEqualToThreshold
      Dimensions:
        - Name: FunctionName
          Value: !Sub '${ProjectName}-main-${Environment}'
      AlarmActions:
        - !Ref AlarmNotificationTopic
      TreatMissingData: notBreaching

  LambdaConcurrentExecutionsAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub '${ProjectName}-lambda-high-concurrency-${Environment}'
      AlarmDescription: 'Lambda concurrent executions are high'
      MetricName: ConcurrentExecutions
      Namespace: AWS/Lambda
      Statistic: Maximum
      Period: 300
      EvaluationPeriods: 2
      DatapointsToAlarm: 2
      Threshold: 80  # 80% of reserved concurrency (100)
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: FunctionName
          Value: !Sub '${ProjectName}-main-${Environment}'
      AlarmActions:
        - !Ref AlarmNotificationTopic
      TreatMissingData: notBreaching

  # API Gateway Alarms
  ApiGatewayHighLatencyAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub '${ProjectName}-api-high-latency-${Environment}'
      AlarmDescription: 'API Gateway latency is high'
      MetricName: Latency
      Namespace: AWS/ApiGateway
      Statistic: Average
      Period: 300
      EvaluationPeriods: 3
      DatapointsToAlarm: 3
      Threshold: 10000  # 10 seconds
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: ApiName
          Value: !Sub '${ProjectName}-api-${Environment}'
      AlarmActions:
        - !Ref AlarmNotificationTopic
      TreatMissingData: notBreaching

  ApiGatewayHighErrorRateAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub '${ProjectName}-api-high-error-rate-${Environment}'
      AlarmDescription: 'API Gateway 4XX/5XX error rate is high'
      MetricName: 4XXError
      Namespace: AWS/ApiGateway
      Statistic: Sum
      Period: 300
      EvaluationPeriods: 2
      DatapointsToAlarm: 2
      Threshold: 10
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: ApiName
          Value: !Sub '${ProjectName}-api-${Environment}'
      AlarmActions:
        - !Ref AlarmNotificationTopic
      TreatMissingData: notBreaching

  ApiGateway5XXErrorAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub '${ProjectName}-api-5xx-errors-${Environment}'
      AlarmDescription: 'API Gateway 5XX errors detected'
      MetricName: 5XXError
      Namespace: AWS/ApiGateway
      Statistic: Sum
      Period: 300
      EvaluationPeriods: 1
      DatapointsToAlarm: 1
      Threshold: 1
      ComparisonOperator: GreaterThanOrEqualToThreshold
      Dimensions:
        - Name: ApiName
          Value: !Sub '${ProjectName}-api-${Environment}'
      AlarmActions:
        - !Ref AlarmNotificationTopic
      TreatMissingData: notBreaching

  # DynamoDB Alarms
  DynamoDBHighReadThrottleAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub '${ProjectName}-dynamodb-read-throttles-${Environment}'
      AlarmDescription: 'DynamoDB read throttles detected'
      MetricName: ReadThrottledEvents
      Namespace: AWS/DynamoDB
      Statistic: Sum
      Period: 300
      EvaluationPeriods: 1
      DatapointsToAlarm: 1
      Threshold: 1
      ComparisonOperator: GreaterThanOrEqualToThreshold
      Dimensions:
        - Name: TableName
          Value: !Sub '${ProjectName}_Sessions_${Environment}'
      AlarmActions:
        - !Ref AlarmNotificationTopic
      TreatMissingData: notBreaching

  DynamoDBHighWriteThrottleAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub '${ProjectName}-dynamodb-write-throttles-${Environment}'
      AlarmDescription: 'DynamoDB write throttles detected'
      MetricName: WriteThrottledEvents
      Namespace: AWS/DynamoDB
      Statistic: Sum
      Period: 300
      EvaluationPeriods: 1
      DatapointsToAlarm: 1
      Threshold: 1
      ComparisonOperator: GreaterThanOrEqualToThreshold
      Dimensions:
        - Name: TableName
          Value: !Sub '${ProjectName}_Sessions_${Environment}'
      AlarmActions:
        - !Ref AlarmNotificationTopic
      TreatMissingData: notBreaching

  DynamoDBHighErrorRateAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub '${ProjectName}-dynamodb-errors-${Environment}'
      AlarmDescription: 'DynamoDB errors detected'
      MetricName: SystemErrors
      Namespace: AWS/DynamoDB
      Statistic: Sum
      Period: 300
      EvaluationPeriods: 1
      DatapointsToAlarm: 1
      Threshold: 1
      ComparisonOperator: GreaterThanOrEqualToThreshold
      Dimensions:
        - Name: TableName
          Value: !Sub '${ProjectName}_Sessions_${Environment}'
      AlarmActions:
        - !Ref AlarmNotificationTopic
      TreatMissingData: notBreaching

  # S3 Alarms
  S3HighErrorRateAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub '${ProjectName}-s3-errors-${Environment}'
      AlarmDescription: 'S3 error rate is high'
      MetricName: 4xxErrors
      Namespace: AWS/S3
      Statistic: Sum
      Period: 300
      EvaluationPeriods: 2
      DatapointsToAlarm: 2
      Threshold: 10
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: BucketName
          Value: !Sub '${ProjectName}-uploads-${Environment}'
      AlarmActions:
        - !Ref AlarmNotificationTopic
      TreatMissingData: notBreaching

  # Custom Application Metrics
  FileProcessingFailureAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub '${ProjectName}-file-processing-failures-${Environment}'
      AlarmDescription: 'File processing failure rate is high'
      MetricName: ProcessingFailures
      Namespace: ExcelTemplateMapper
      Statistic: Sum
      Period: 300
      EvaluationPeriods: 2
      DatapointsToAlarm: 2
      Threshold: 5
      ComparisonOperator: GreaterThanThreshold
      AlarmActions:
        - !Ref AlarmNotificationTopic
      TreatMissingData: notBreaching

  # Composite Alarm for Overall Health
  ApplicationHealthAlarm:
    Type: AWS::CloudWatch::CompositeAlarm
    Properties:
      AlarmName: !Sub '${ProjectName}-overall-health-${Environment}'
      AlarmDescription: 'Overall application health check'
      AlarmRule: !Sub |
        ALARM(${LambdaHighErrorRateAlarm}) OR 
        ALARM(${ApiGatewayHighErrorRateAlarm}) OR 
        ALARM(${DynamoDBHighErrorRateAlarm}) OR
        ALARM(${S3HighErrorRateAlarm})
      AlarmActions:
        - !Ref AlarmNotificationTopic
      OKActions:
        - !Ref AlarmNotificationTopic

  # Cost Alarm
  EstimatedChargesAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub '${ProjectName}-high-costs-${Environment}'
      AlarmDescription: 'AWS charges are higher than expected'
      MetricName: EstimatedCharges
      Namespace: AWS/Billing
      Statistic: Maximum
      Period: 86400  # Daily
      EvaluationPeriods: 1
      DatapointsToAlarm: 1
      Threshold: 100  # $100
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: Currency
          Value: USD
      AlarmActions:
        - !Ref AlarmNotificationTopic
      TreatMissingData: notBreaching

Outputs:
  SNSTopicArn:
    Description: ARN of the SNS topic for alarm notifications
    Value: !Ref AlarmNotificationTopic
    Export:
      Name: !Sub '${ProjectName}-alarm-topic-${Environment}'

  ApplicationHealthAlarm:
    Description: Composite alarm for overall application health
    Value: !Ref ApplicationHealthAlarm
    Export:
      Name: !Sub '${ProjectName}-health-alarm-${Environment}'